# Generated by Django 5.2.8 on 2025-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_userprofile_auditlog_description_auditlog_new_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
